### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by ghost** [angelleye/paypal-ipn-template#8]
When I try the install I just keep getting this

Database Error
--
Message: | Could not open database: cl20-shoppymc.
MySQL Error: | You  have an error in your SQL syntax; check the manual that corresponds to  your MariaDB server version for the right syntax to use near '-shoppymc'  at line 1
Date: | Sunday, September 30, 2018 at 2:44:48 PM
Script: | /bata1/admin/install/create-db-tables.php
Referer: | https://xxx.xx.xx/bata1/admin/install/

I think I have found the error its if the database has a "-" in it, it won't prosses it
As I have tried it on my home server and it went through without any issues

I have asked my hosting provider if I could have a database without the "-" in it but they won't let me do that so I don't know what else I can do

**Comment by deepakmaurya** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done**

<hr>

**Worker have applied to start work.**

Below user(s) claimed they can complete the work within defined time period.

Please review their action plans below:

**1) <a href='https://sandbox.gitworkdone.com/profile/paypal_fac'>paypal_fac</a> has been approved to work.**
                
**Message:** I would like to start this project.




<a href='https://sandbox.gitworkdone.com/issue/install-errors'>Click Here to view more</a> on GitWorkDone Bounty detail page.

**Comment by deepakmaurya** [comment]
Issue Status: 1. Open 2. **Started**  3. Submitted 4. Done

<hr>

**Work has been started.**

**<a href='https://sandbox.gitworkdone.com/profile/paypal_fac'>paypal_fac</a> has been approved to start work.**

<hr />

**Message:** Yes, you can work on this!


<a href='https://sandbox.gitworkdone.com/issue/install-errors'>Click Here to view more</a> on GitWorkDone Bounty detail page.

**Comment by deepakmaurya** [comment]
**<a href='https://sandbox.gitworkdone.com/profile/angelleye'>https://sandbox.gitworkdone.com/profile/paypal_fac</a> Work has been approved by <a href='paypal_fac'>angelleye</a>.**
<hr />

**Message:** Thanks for the good work!


<a href='https://sandbox.gitworkdone.com/issue/install-errors'>Click Here to view more</a> on GitWorkDone Bounty detail page.

**Comment by angelleye** [comment]
@light-angel  Sorry for confusion here.  I was using this ticket to test a new project we're working on.  :)

**Comment by ghost** [comment]
ok I was starting to get my hopes up lol I have been trying to fix myself but not getting anywhere fast with it

**Comment by angelleye** [comment]
@light-angel Sorry about that.  I actually never saw your initial post here.

Unfortunately, this template is out-dated.  I'm guessing the problem you're facing is something to do with PHP version.  This isn't going to work on anything above 5.6, I don't think.

I've been meaning to build a new version of it.  One that combines IPN and webhooks, since that's what PayPal now uses with their REST APIs.

**Comment by devchristina2** [comment]
Hi @deepakmaurya,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
