### ISSUE TITLE
Deprecated: Methods

### ISSUE THREAD

**Issue by wethecom** [angelleye/paypal-ipn-template#9]
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; WA_AltClassIterator has a deprecated constructor in xxxxxxxxxxxxxxx/pay/admin/recurring-payment-profiles-results.php on line 156

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at xxxxxxxxxxxxxxx/pay/admin/recurring-payment-profiles-results.php:156) in xxxxxxxxxxxxxxxxx/pay/admin/recurring-payment-profiles-results.php on line 4

**Comment by angelleye** [comment]
I'm very sorry for the delay replying here.  I've been focused on our own help desk and lost track of my GitHub notifications there for a little bit.  Didn't mean to leave you hanging!

For future reference, this sort of thing would be best to submit to our help desk directly at https://angelleye.com/support.  This will get into our standard queue where we can prioritize and resolve issues accordingly.

I will go ahead and create this ticket there, and we'll update you here when we have more info, but in the future please use our help desk.  Thanks!

**Comment by devchristina2** [comment]
Hi @wethecom,

Thank you for reaching out and submitting an issue on our GitHub repository.

We wanted to inform you that we’ve temporarily paused active support for this repository and will close all open issues, including this one. If you require further assistance or have additional questions, please submit a support ticket through our [Help Center](https://angelleye.atlassian.net/servicedesk/customer/portals), where our support team will be happy to assist you.

We appreciate your understanding and apologize for any inconvenience. Thank you for being part of our community!

Thanks, Christina.
